name: Model Evaluation

on:
  push:
    branches: [ main ]
    paths:
      - "evaluation/**"
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
    prettier:
        runs-on: ubuntu-latest
        env:
          OPENAI_HOST: ${{ vars.OPENAI_HOST }}
          OPENAI_GPT_MODEL: ${{ vars.OPENAI_GPT_MODEL }}
          AZURE_OPENAI_EVAL_DEPLOYMENT: ${{ vars.AZURE_OPENAI_EVAL_DEPLOYMENT }}
          AZURE_OPENAI_SERVICE: ${{ vars.AZURE_OPENAI_SERVICE }}
          AZURE_SEARCH_SERVICE: ${{ vars.AZURE_SEARCH_SERVICE }}
          AZURE_SEARCH_INDEX: ${{ vars.AZURE_SEARCH_INDEX }}
          AZURE_PRINCIPAL_ID: ${{ vars.AZURE_PRINCIPAL_ID }}
        steps:
            - uses: actions/checkout@v4
            - name: Run evaluations
              run: |
                cd ./evaluation
                pip install -r scripts/requirements.txt
                python -m script evaluate --config=./example_config.json --numquestions=10
